### ISSUE TITLE
window.displacejs.destroy();

### ISSUE THREAD

**Issue by wandering-scientist** [catc/displace#13]
I couldn't Figure out how this works or removes the event listener, can you please guide me on its usage
thanks
tbh great library.

**Comment by catc** [comment]
To destroy you have to call the `destroy` method on the displace instance you created. So you need a reference to the displace instance you create earlier.

```js
// create displace instance
const d = displace(document.querySelector('.some-div'), {});

// destroy the instance
d.destroy()
```

Let me know if you have any other questions.
