### ISSUE TITLE
pinching to zoom in or out the element bigger

### ISSUE THREAD

**Issue by mfabing** [catc/displace#2]
feature request.
Would it be possible to add the possibility to pinch the element with 2 fingers that would enable the user to zoom-in (increase the size of the element) or zoom-out (decrease the size of the element)?

**Comment by rohmanhm** [comment]
That's great idea

**Comment by catc** [comment]
After investigating a similar issue - https://github.com/catc/displace/issues/10 - I decided that this is out of scope of the minimal features this library should have.
