### ISSUE TITLE
Can't type text on inputs?

### ISSUE THREAD

**Issue by khullah** [catc/displace#3]
Here's a ridiculous example: https://jsfiddle.net/yyu3bsxs/

**Comment by catc** [comment]
I'll try to get a fix in this week.

**Comment by khullah** [comment]
Great. I'll try to see if I can get anything as well, thanks

**Comment by khullah** [comment]
Hey, after your correction, now I can type on inputs, but not move then. I've figured out that removing this piece of code solves the problem (it's so little I didnt make a PR):

```
	function mousedown(e) {
		// allow for selection of text in inputs/textareas
		var target = e.target.tagName.toLowerCase();
		if (target === 'input' || target === 'textarea') {
			return;
		}
               ...
```

The problem you commented will remain, though.
An updated plunker: https://embed.plnkr.co/0ijox3CrRyrflbYnCySx/

**Comment by catc** [comment]
In your plunker example, you can move both the 2nd and 3rd items, and still type in the input too? I don't see the issue?

**Comment by khullah** [comment]
Yes, but only after commenting the code I've mentioned.
Saved a 3rd version, with code uncommented, take a look: https://plnkr.co/edit/0ijox3CrRyrflbYnCySx?p=preview

**Comment by catc** [comment]
I'll get a fix in this weekend.

**Comment by catc** [comment]
Added the `highlightInputs` option, which in your case would just set to `true` and it should work. Let me know if you have any other issues.

**Comment by khullah** [comment]
Nice! Thanks.
Will do, glad I can help this project.
