### ISSUE TITLE
Support dragging (and dropping) multi-touch/multiple items at once

### ISSUE THREAD

**Issue by dumblob** [catc/displace#34]
I like the simplicity and functionality of this library! Thanks also for the online demos - they're really well prepared and necessary.

I wonder whether this could be efficiently used also for long lists (thousands of items) wherease one would be free to select multiple items and then drag them all at once.

Any suggestions?

**Comment by catc** [comment]
I haven't experimented with that before, but it might be doable. Although if you're planning to do list sorting you're better off with something like react-beautiful-dnd or dragula.
