### ISSUE TITLE
Possible bug on displace.reinit()

### ISSUE THREAD

**Issue by caracal7** [catc/displace#5]
I have set of divs with drag handle and on "window.resize" event I call "displace.reinit()" on each div.
And after that then I try to drag, drag mode not stoped after mouseup.

**Comment by caracal7** [comment]
`

    //  Not working 
    window.onresize = () => Items.forEach(item => item._displace.reinit());


    //  Working
    window.onresize = () => Items.forEach((Item) => {
        Item._displace.destroy()
        Item._displace = displace(Item.container, {
            constrain: true,
            handle: Item.handle
        }); 
     });



`

**Comment by catc** [comment]
I'll investigate. Can you provide a simple jsfiddle/jsbin of the issue?
