### ISSUE TITLE
displace is not defined

### ISSUE THREAD

**Issue by jorgemonte** [catc/displace#8]
I was trying to implement the library to my code and received this error message. Decided to had a look at the code and realized that the variable is called displacejs. Changing to :
```
const el = document.querySelector('#ball-1');
displacejs(el);
```
Now, no error messages are appearing. I'd just like to ask if the code and documentation are not matching of ir I am looking at the wrong place. Thank you!

**Comment by catc** [comment]
If you look at https://github.com/catc/displace#getting-started, it's imported as `displacejs` if you're using the global dist script. I just alias via `const displace = window.displacejs;` so it's consistent with the rest of the documentation.

Closing, but lemme know if you have any other questions.

**Comment by jorgemonte** [comment]
Thank you very much, it's just that I am still not comfortable with Javascript, lol, your website documentation is  awesome. It was just not clear to me because of my lack of experience.

**Comment by LenaTevar** [comment]
Hello! I'm also using displace for school, or I try to... I must be missing something. 
I get
`TypeError: Error resolving module specifier: displacejs`
from the import
```
import displace from 'displacejs'

const element = document.querySelector('.box')

displace(element)
```
I used npm to install it, no errors showing, am I missing something else?
